<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Mail;
use App\Mail\Reminder as ReminderEmail;


class Reminder extends Command
{
    /**
     * Send reminder email to submit form data.
     *
     * @var string
     */
    protected $signature = 'command:reminder {--all=false}';


    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Send reminder email to submit form data.';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
      if($this->option('all')){
          $emails = [
            // ['Sarvar Kumar',\Config('oly.developer_email')],
            ['Sarvar Kumar','sarvarrose@gmail.com'],
            ['Komal sen', '24komalsen@gmail.com'],
            ['Vinod Madan', 'vinodmadan1968@gmail.com'],
          ];
        }else{
          $emails = [
            // ['Sarvar Kumar',\Config('oly.developer_email')],
            // ['Vinod Madan','vinodmadan1968@gmail.com'],
            // ['Komal sen','24komalsen@gmail.com'],
            // ['Dr. Saroj Kumar Satpathy','drsatapathysarojkumar@gmail.com'],
            // ['Mr. Mustaque Ahmed','mushtaque.ahmad@medanta.org'],
            // ['Dr. James','james.elangbam@gmail.com'],
            // ['Mr. Happy','addannex@yahoo.in'],
            // ['Dr. Arunp Baro','dranupbaro@yahoo.co.in'],
            // ['Mr. Jahangir Alam','alamnursinghome@gmail.com'],
            // ['Mr. Rajesh Sahu','rajesh.sahu@amribbsr.in'],
            // ['Mr. Nil Kailash Singh','maintenance@babinadiagnostics.com'],
            // ['Mr. Chranjib Kmakar','sramajibihospital@gmail.com'],
            // ['Dr. Sujit Saikia','dr.sujitsaikia@gmail.com'],
            // ['Mr. Patowary','bme.cihsr@gmail.com'],
            // ['Dr. Abhijit Balmah ','dishosp@gmail.com'],
            // ['Dr. M T Belho','drsenobelho@yahoo.co.in'],
            // ['Mr.Soumendra Behera','geetadiagnosticscentre@gmail.com'],
            // ['Dr. Dulal Chandra','dulalhatirpithy@gmail.com'],
            // ['Sr. Asit Kumar Mishra','amit.rai@mjunction.in'],
            // ['Ms. Maumita Chakraborty','chakrabarty.maumita@gmail.com'],
            // ['Dr. S N Mondal','urologycnmch@gmail.com'],
            // ['Dr. Ganesh Jha','jha.ganesh@rediffmail.com'],
            // ['Datta Ji','duttaji.vimalhospital@gmail.com'],
            // ['Ashok Kumar Ram','hussain.nabuat89@gmail.com'],
            // ['Mr.Raj Kishore Jajodia ','gnhburla@gmail.com'],
            // ['Dr. Pc Dalai','igkchospital@gmail.com'],
            // ['Dr. Pritam','preetam.nath@kims.ac.in'],
            // ['Chakraborty ','akchakrawarty@gmail.com'],
            // ['Mr Thaa ','lcmclawngtlai@gmail.com'],
            // ['Sister Jessy','mercyhospital.jsr@gmail.com'],
            // ['Dr. Barnad','nagahospitalauthoritykohima@gmail.com'],
            // ['Mr Bikram Sil','bikram.sil@narayanahealth.org'],
            // ['Mr. Sombit Sahoo','bme.neigrihms@gmail.com'],
            // ['Mr Alam','bme.darjeeling1@gmail.com'],
            // ['Dr. Biswsajit Gogoi','biswajitgogoi_db@yahoo.com'],
            // ['Sayan Bhadra','sayan.bhadra@narayanahealth.org'],
            // ['Dr. Kaku','drkaku.rims@gmail.com'],
            // ['Dr. Deka','ddeka.dkd@gmail.com'],
            // ['Rabi Das','rnkdgp.op@gmail.com'],
            // ['Priyaranjan Kalita','smhospital.dc@gmail.com'],
            // ['Dr. C R Panda','panda.cr@hotmail.com'],
            // ['Dr. C R Panda','crpanda58@gmail.com'],
            // ['Mr Kunjakishore ','lissetsacredheart@gmail.com'],
            // ['Dr. Sk Biswas','skbiswas@saildsp.co.in'],
            // ['Tapas','tmc.agt@gmail.com'],
            // ['Dr. Kevin Momin','turacivilhospital@gmail.com'],
            // ['Dr. Aparjita Sandilya','urovisionhospital@gmail.com'],
            // ['Dr. S K Dalai','docsangramdolai123@gmail.com'],
            // ['Pranbir Patel','steelcityclinic@gmail.com'],
            // ['Dr. Bhaskar Hazarika','bhaskar.1hazarika@gmail.com'],
            // ['Dr. Sanjay Kumar Gupta','dr.skgupta94@gmail.com'],
            // ['Dr. J A Khan','jakhan22@gmail.com'],
            // ['Dr. Vinay Pratap','vinay94311@gmail.com'],
            // ['Dr. Amit Kumar','dramitskmch99@gmail.com'],
            // ['Arvind Kuamr','akarvind16@gmail.com'],
            // ['Sujay Saha','sujoyy.saha@gmail.com'],
            // ['Mr. Shibananda','bme@rajmedicity.com'],
            // ['Dr. Ssivaresmi Unnuthan','sivaresmi@gmail.com'],
            // ['Dr. Sanjeev Kumar Jha','drjha78@yahoo.in'],
            // ['Mr.Mihir Mohanta','mihir.mohanta@carehospitals.com'],
            // ['Dr. Abhishek Mishra','ediagnosis@gmail.com'],
            // ['Baiar Kupar Suting','baiarkupar86@gmail.com'],
            // ['Dr.Amalan Jyoti Sharma','hayatbme@gmail.com'],
            // ['Manoj Kumar','manojkumar0072012@gmail.com'],
            // ['Divya Prakash','purchase.narayanmedicalcollege@gmail.com'],
            // ['Mr Anup Sharma','biomedanup06@gmail.com'],
            // ['Biswajit','facilityhead.sdc@sunhospitals.com'],
            // ['Dr. Seema Sahai','drsimapatna@gmail.com'],
            // ['Dr. Amit','dramitgour@gmail.com'],
            // ['Dr. Meena Jain','meena.Jain@gmail.com'],
            // ['Dr. Sachin Batra','sachinbatra08@gmail.com'],
            // ['Mr. Shahjanand','shahajanand.singh@narayanahealth.org'],
            // ['Ronit','ronit.kumar@fortishealthcare.com'],
            // ['Pradeep Kumar','biomed@isiconline.org'],
            // ['Dr. Lokesh','purchaseksch@gmail.com'],
            // ['Sunil Yadav','biomedical@actionhospital.com'],
            // ['Mrs, Lata Joshi','materials@sitarambhartia.org'],
            // ['Mrs, Lata Joshi','lata.joshi@sitarambhartia.org'],
            ['Ms. Sjhivan','vpcipur@gmail.com'],
            ['Vikas','v4vikaskhatri@gmail.com'],
            ['Sahahi Kuamr','shashi.kumar@maxhealthcare.com'],
            ['Dilip Kumar Singh','dilipkumarsingh7441@gmail.com'],
            ['Dr. Gurjar','gurjarhospital@yahoo.com'],
            ['Dr.Ashok Jain','pukhratan@yahoo.com'],
            ['Dr. Anand Singhai','anandsinghai01@yahoo.com'],
            ['Saranpreet Singh','saranpreetsingh2006@gmail.com'],
            ['Vinod Lakhanpal','vinodlakhanpal@gmail.com'],
            ['Dr. S.K. Kala','srkallahospital@rediffmail.com'],
            ['Mr. Pankaj','bme@gbhamerican.com'],
            ['Mr. Piyush Kanodia','bme@geetanjaliuniversity.com'],
            ['Dr. Sanjay Singla','drsanjaysingla@gmail.com'],
            ['Dr. Dhruva Chaudhary','dhruvachaudhry@yahoo.co.in'],
            ['Ajit','bme.manager@moolchandhealthcare.com'],
            ['Abhishek Kumar','abhishekkumar@batrahospitaldelhi.org'],
            ['Ms.Anju ','biomed@metrohospitalfaridabad.com'],
            ['Mr. Abijit','akumar4@ilbs.in'],
            ['Dr. Sunil Arya','drsunilarya12@gmail.com'],
            ['Akshay Sandhu ','asandhu17@gmail.com'],
            ['Mv Suraj','biomedengg@bimrhospital.com'],
            ['Dr. Jk Thani','drpp.work@gmail.com'],
            ['Tikam Pal','biomedical@medishinehealth.com'],
            ['Dr. Manoj Kumar','drmanoj63@gmail.com'],
            ['Dr. Kartik Goyal','Kartikg24@gmail.com'],
            ['Ashish Jindal','parminder.jassal@fortishealthcare.com'],
            ['Ashish Jindal','ashish_jindal24@yahoo.com'],
            ['Dr. Deepak ','Saransing1234@gmail.com'],
            ['Dr. Shabbir Hussain','docshabbir@rediffmail.com'],
            ['Somil Jain','lnctuniversity@gmail.com'],
            ['Subrata','siwach777@gmail.com'],
            ['Subrata','siwach777@gmail.com'],
            ['Dr. Naresh','bio@jmh.in'],
            ['Lalit Kumar','lalit.kumar1@fortishealthcare.com'],
            ['Dr. Pramod Kumar Mittal','dr_parmod@yahoo.co.in'],
            ['S K  Mishra ','appolofaridabad@yahoo.com'],
            ['Rajesh','rajesh.kumar@fortishealthcare.com'],
            ['Mr. Jag','kidneyhospital@yahoo.com'],
            ['Mr. Vipul','bme.pb@mahdelhi.org'],
            ['Mrs. B S Rtathi','biomedical_eng@psri.net'],
            ['Mr. Rizwan','rizvi.rizwan251@gmail.com'],
            ['Pawan Kumar','pawan.kumar0@fortishealthcare.com'],
            ['Rajeev Nair','biomedical_indore@apollohospitals.com'],
            ['Dr. Narendra Singh Yadav','drnsyadav@outlook.com'],
            ['Dr. Susheel','Sheel_doc@rediffmail.com'],
            ['Dr. Sharvan Malvi','malvihospital@hotmail.com'],
            ['Dr. Ashish Dubey','drashishdubeybpl@gmail.com'],
            ['Dr. Anju Gupta','anjuragupta7@gmail.com'],
            ['Abinav','bme.aadhar@gmail.com'],
            ['Dr. Raeksh Sharma','drrakeshsms2001@gmail.com'],
            ['Dr. Sanjay Kumar','gastrocarebpl@rediffmail.com'],
            ['Arjun Singh','bme@grecianhospital.com'],
            ['Akshay','avhrc@rediffmail.com'],
            ['Dr. Vinay Poonia','drvinaypoonia@gmail.com'],
            ['Dr. Chatley','girishchatley@gmail.com'],
            ['Dr. S K Goyal','goyalendoscopykota@yahoo.in'],
            ['Dr. Devendra Singh','devsvirdi@yahoo.com'],
            ['Dr, Bharat Katkar','rukhsarharda009@gmail.com'],
            ['Mahednra Singh','raj.bme29@gmail.com'],
            ['Dr. Shamendra Saraf','sarraf59@gmail.com'],
            ['Dr. Naveen Kumar','nksaurot@yahoo.com'],
            ['Ms. Nish Nishad','bme@venkateshwarhospitals.com'],
            ['Durga Pradeep Bolla','durga.bolla@ckbirlahospitals.com'],
            ['Sachin Kale','sachin.kale@saimsonline.com'],
            ['Dr. Vineet Nanja Jain','najavineet@gmail.com'],
            ['Dr. P Hemant Kumar','nia-rj@nic.in'],
            ['Lalit Saini','LALIT.SAINI@NARAYANAHEALTH.ORG'],
            ['Dr.Rohit Gupta','drrohitgupta16@yahoo.co.in'],
            ['Mr Rabinder','rabindraprasad456@gmail.com'],
            ['Peeyush','biomedical@elmcindia.org'],
            ['Mrinal','mayo_medical@yahoo.com'],
            ['Dr. Samim','drshameem123@gmail.com'],
            ['Ram','info@scpmhospital.com'],
            ['Dr. Ratnesh Pawar','ratneshpawar@gmail.com '],
            ['Raju','samvednahospitalvns@gmail.com'],
            ['Dr. D R Singh','drshospital@rediffmail.com'],
            ['Dr. Shemeem','drshameem123@gmail.com'],
            ['Dr. Vikas Sengar','drvikassengar@yahoo.co.in'],
            ['Dr. Sharad Agarwal','drsharad67@gmail.com'],
            ['Dr. Richa','jkci1963@gmail.com'],
            ['Robin','biomedical.dept@tmu.ac.in'],
            ['Dr. Veena (Husband) Dr. Veenas Husband Has Given The Feedback)','gnhbhinga@gmail.com'],
            ['Navneet Madan','navneet14.madan@gmail.com'],
            ['Dr.Sharad Chandra','sharadurvashi@gmail.com'],
            ['Dr. L B Gupta ','drlbgupta@gmail.com'],
            ['Dr. Lalith','lalit.mtr@gmail.com'],
            ['Professor A S Kodla','medalliontradingcorp@rediffmail.com'],
            ['Ghulamkhader','medalliontradingcorp@rediffmail.com'],
            ['Dr. Daksha Khurana','dr.dakshkhurana79@gmail.com'],
            ['Mr. Rajat Agarwal','garghospital2010@gmail.com'],
            ['Dr. Abhijeet','dr.abhijat@gmail.com'],
            ['Dr., Narseem','khannaseem2010@gmail.com'],
            ['Dr. Akshay','aabhaaykumaar@rediffmail.com'],
            ['Dr. V K Mishra','mishravk2k@hotmail.com'],
            ['Abhishek','rumahospitals@gmail.com'],
            ['Dr. Saurabh','ssdrsaurabh@gmail.com'],
            ['Suresh','suresh@gmail.com'],
            ['Zahoon','medalliontradingcorp@rediffmail.com'],
            ['Dr. Ajay Shukla','ajaysonushuklaa@gmail.com'],
            ['Dr. Lovee Malhotra','shubhmehrotra@hotmail.com'],
            ['Dr. Siddharth','sidd.agarwal@gmail.com'],
            ['Dr. Rakesh','rakeshsrivastavaent@gmail.com'],
            ['Harish','aadithyaadhikarihospital@gmail.com'],
            ['Prakash','adaudp@gmail.com'],
            ['Dr. B Na Patil','patilbn69@gmail.com'],
            ['Basavaraj','basavaraj_m@apollohospitals.com'],
            ['Mr. Mahanthesh','biomedical.mys@cauveryhearthospital.org'],
            ['Ms. Prma','prema_cmhblr@rediffmail.com'],
            ['Mr. Venkatesh','biomed.whitefield@columbiaindiahospitals.com'],
            ['Mohammed Raffe','biomedsupervisor.yeshwanthpur@columbiaindiahospitals.com'],
            ['Dr. Ravindra B Haded','rbdhaded@gmail.com'],
            ['Dr. Dharma Reddy','drdharmareddyb@gmail.com'],
            ['Dr. Nagraj Jkotli','drnagarajkotli@gmail.com'],
            ['Dr. Nikil Oswal','drnkoswal@gmail.com'],
            ['Dr. Pradeep','pradeepjk80@gmail.com'],
            ['Dr. Rajendra','drgrajendra77@gmail.com'],
            ['Madan','bm.excelcare@gmail.com'],
            ['Harshitha','harshitha.hulikal@fortishealthcare.com'],
            ['Mr. Raghavbendra','igich.bme@gmail.com'],
            ['Mr. Rafiqsangam','rafiqsangam1234@gmail.com'],
            ['Ram Mohan','nramamohana@gmail.com'],
            ['Dr. Ravindra','drravindrabs@gmail.com'],
            ['Mr. Kumaraswamy','gomasa.kumaraswamy@narayanahealth.org'],
            ['Jeyakumar A','bme.krm@apollospectra.com'],
            ['Ms. Sreenivas K','sreenivask@hindujasindhihospital.com'],
            ['Amith','amitkumar.mysore@srl.In'],
            ['Dr. Ravi Kumar','karturiravi@yahoo.co.uk'],
            ['Mr. Ramesh','bmesimsrc@gmail.com'],
            ['Ms. Llalita','theresahospital@gmail.com'],
            ['Ms. Shridevi','shridevi.ashrith@gmail.com'],
            ['Rahulraj','bme@stmarthas.in'],
            ['Mr. Prakash','bapujihospital@rediffmail.com'],
            ['Dr. Sridhar','vvrchaitanyahospitals@gmail.com'],
            ['Mr. Sabari.Gs','sabari.gs@fortishealthcare.com'],
            ['Vijay N','purchase@jindalnaturecure.org'],
            ['Mr. Gowtham Bme','gowtham.ramdasbhat@althea-group.com'],
            ['Mr. Gowtham Bme','purchase.kh@manipal.edu'],
            ['Kooteshwar','koteeswara.r@stjohns.in'],
            ['9845976666- Ms. Vasth Refed To Dr. Savitha','admin@padmashree.in'],
            ['Ms. Lavanya ( Mr. Pawan)','biomedical.blr@rainbowhospitals.in'],
            ['Sakthi Kumar','sakthi.globalhospital@gmail.com'],
            ['Mohini','mohini.heamala@manipalhospitals.com'],
            ['Mr Angelo','blr.biomedical@hcgel.com'],
            ['Lakshmi Nataraja','laxmi010@gmail.com'],
            ['Akhil','biomed.sarjapur@columbiaindiahospitals.com'],
            ['Dr. Sasidar','aprasasi@gmail.com'],
            ['Rajesh','rajesh_bems@apollohospitals.com'],
            ['Dr. Castro','aristohospital@gmail.com'],
            ['Siva','mail@cetharhospitals.com'],
            ['Dr. Mahendran','drniresh@gmail.com'],
            ['Balaji','biomedical@chettinadhealthcity.com'],
            ['Dr.Selvaraj','dharanhospital@gmail.com'],
            ['Dr. Kannan','malarkan08@gmail.com'],
            ['Dr. Shafique','sharazi16@gmail.com'],
            ['Dr. Jyothi Basu ','djyotibasu@hotmail.com'],
            ['Dr. Saravanan Rajamanikam ','saravana@email.com'],
            ['Bharani','bme@drmohans.com'],
            ['Premalatha','swathiprema@gmail.com'],
            ['Dr. Prabhakaran','sathyamhospital@gmail.com'],
            ['Saravana','eshospital@gmail.com'],
            ['Devarayan ','essvee@gmail.com'],
            ['Muthuraman','muthuraman.g@fortishealthcare.com'],
            ['Narasimhan','biomedical1965@gmail.com'],
            ['Padmanaban','nabhanpadma77@gmail.com'],
            ['Ramanathan','ramanathan@gmail.com'],
            ['Dr. Saravanan','gdmchdpi@gmail.com'],
            ['Gopal Swamy','irtpmcdean@gmail.com'],
            ['Karthik','kvtspeciality@gmail.com'],
            ['Shanmugam','spmmhospital@gmail.com'],
            ['Tafic','meenakshihospital12@gmail.com'],
            ['Babu Antony','babusrutha@gmail.com'],
            ['Prabhakar ','cbe@pimsmmm.net'],
            ['Ganapathy','mrajau10@gmail.com'],
            ['Dr. Vijay','vijay_aqu@yahoo.com'],
            ['Dr. Preabhu Shankar','info@shanmugahospital.com'],
            ['Dr. Rajesh','admin@srigokulamhospital.com'],
            ['Eeshwaran','biomedicalslims@gmail.com'],
            ['Ganesh','ganeshbme4@gmail.com'],
            ['Jayakumar','svmch_pondy@yahoo.com'],
            ['Sister Rajina','sjhcpdy@yahoo.com'],
            ['Dr. Kalpana','urologykmc@gmail.com'],
            ['Saravanan','biomedical@vshospitals.com'],
            ['Baskar','biomedical@vadamalayan.org'],
            ['Prabhakaran','pranavsalem@gmail.com'],
            ['Govindharaj','harshamitrahr@gmail.com'],
            ['Dr. Natarajan','mediashok@gmail.com'],
            ['Ms. Subrathira','info.smc@saveetha.com'],
            ['Kannan','kannanbiomed@gmail.com'],
            ['Balaji','biomedical@chettinadhealthcity.com'],
            ['Dr. Arun','starhospitalsattur@gmail.com'],
            ['Dr. Sivaraj','lotus.erobio@gmail.com'],
            ['Dr.Ramsamy','drramnallu@gmail.com'],
            ['Dr. Meeran','smsmeeran@gmail.com'],
            ['Dr. Ramraj','chitralagesan@gmail.com'],
            ['Dr.Mohammad Shihab','shihabpanchili@gmail.com'],
            ['Dr.Robert Panakkal','panakkal@gmail.com'],
            ['Dr. Sree Kumar','sreekumarathiyarath@gmail.com'],
            ['Dr.Biju','ikbiju72@yahoo.com'],
            ['Dhanasekar','deenhospital@gmail.com'],
            ['Dr. Josy John','joshytjohn@hotmail.com'],
            ['Dr. Shine','drshinebh@yahoo.co.in'],
            ['Dr. Jaison Varghese','drvarghesejaison@gmail.com'],
            ['Dr.K Vinayachandran Nair','kv.nair@rediffmail.com'],
            ['Dr.Prabhakaran','pbpkn2@gmail.com'],
            ['Dr.Rooby','roobyshaheer@gmail.com'],
            ['Dr. Tom Kurian','tomkurien@rediffmail.com'],
            ['Dr. Shaji','mathamedicalcentre@gmail.com'],
            ['Dr.Sunil Kumar','sunilcalicut@gmail.com'],
            ['Dr. Syed Muhammed ','aikyam1@gmail.com'],
            ['Mr.Yasir','mes.biomedical@gmail.com'],
            ['Mr.Joby K Varghese( Hod Bme)','bio@moscmm.org'],
            ['Mr.Sreenath(Hod Bme)','nsmimskollam@gmail.com'],
            ['Dr.Sandeep','drsandeepgastro@gmail.com'],
            ['Dr. Jaladharan','jeladhar@gmail.com'],
            ['Dr.Swamidasan','drswamidasan@gmail.com'],
            ['Dr.Jose Mathew','josemathew2001@gmail.com'],
            ['Dr.Deepak Thomas','dpkmtm@gmail.com'],
            ['Mr.Rajesh J S( Bme Hod)','js.rajesh1@gmail.com'],
            ['Dr. Roshin Poulose','roshinpoulose@yahoo.com'],
            ['Dr.Sobhana Devi','devi.sobhana@gmail.com'],
            ['Ms.Rejina(Biomed).No User','biomedcal@sevanahospital.org'],
            ['Pavan','MANAGER.BTPHOSPITAL@RDT.CO.IN'],
            ['Not Given By Branch','asrambiomedical@gmail.com'],
            ['Not Given By Branch','srigutindia@yahoo.com'],
            ['Mr. Sai Kiran','asianbiomedical@gmail.com'],
            ['Dr. C Bharavi - Md Dm','bharavicheekati@gmail.com'],
            ['Not Given By Branch','biomedical.mamata@gmail.com'],
            ['Mr. Ramson','ramson1120@gmail.com'],
            ['Not Given By Branch','nthyamagundlam@gmail.com'],
            ['Penchulaya ','biomedical.ngh@gmail.com'],
            ['Not Given By Branch','biomed.psims@gmail.com'],
            ['Dr. Venkateshwaurlu','venkateswarlud87@gmail.com'],
            ['Not Given By Branch','maintenance@aayushhospitals.com'],
            ['Not Given By Branch','madhugastro@gmail.com'],
            ['Dr. Sudhakar','vuluchalasudhakar@gmail.com'],
            ['Mr. Swamy -','swamy013@gmail.com'],
            ['Dr. Hidyatulla Gulfarash (Senior Urologist)','sohnihidayath@gmail.com'],
            ['Not Given By Branch','varmahospitals@gmail.com'],
            ['Mr. Prakash','BIOMEDICALMGR.KHL@KAMINENIHOSPITALS.COM'],
            ['Not Given By Branch','dp15608@gmail.com'],
            ['Not Given By Branch','balutadikonda@gmail.com'],
            ['Dr. Visnu Vardhan Rddy-','avvreddy639@gmail.com'],
            ['Not Given By Branch','superintendentbgh@gmail.com'],
            ['Dr. Ramchcandra ','biomedicalgnt@rameshhospitals.com'],
            ['Not Given By Branch','venkatrs21@yahoo.co.in'],
            ['Mr. Rajarshi/ Mr. Mvt Prasad','biomedical@kimsmedicalcollege.org'],
            ['Prakash','biomedical@kimsmedicalcollege.org'],
            ['Dr. Harish','harishkumaryedla@yahoo.co.in'],
            ['Not Given By Branch','bme@gems.edu.in'],
            ['Not Given By Branch','rkhospital.gajuwaka@gmail.com'],
            ['Dr. Lakshman Chandra','lakshmanachandra@gmail.com'],
            ['Not Given By Branch','dasdeva98@gmail.com'],
            ['Dr. Jignesh Patel','drjigs2712@gmail.com'],
            ['Mitali Patel - Divalata','dhirajbiomedical@gmail.com'],
            ['Dr. Arvind Vikani','vikani@hotmail.com'],
            ['Dr. Chentan Mehta','mehtacn@hotmail.com'],
            ['Dr. K K Rawal','kkrawal@gmail.com'],
            ['Dr. Nikhil Shah','pshahnikhil@gmail.com'],
            ['Dr. Sanjay Popat','sanpopat@rediffmail.com'],
            ['Dr. Vasant Joshi','vasantjoshi70@gmail.com'],
            ['Dr. Vimal B Saradava ','vimaldhara2005@gmail.com'],
            ['Dr. Amit Patel','amitpatelb100@gmail.com'],
            ['Dr. Amit Patel','nitesh00@rediffmail.com'],
            ['Ms. Drashtri ','biomedical.gcri@gmail.com'],
            ['Jignesh Sevak','jigneshjs@charutarhealth.org'],
            ['Dr. Prabhav Antani','info@mmpjhospital.com'],
            ['Dr. Chirag Gangujatia','samarpanjam@gmail.com'],
            ['Ashish Jadav','jadavashish@yahoo.co.in'],
            ['Mueksh','mukesh.patel@sterlinghospitals.com'],
            ['Pankaj Desai','drp_desai@hotmail.com'],
            ['Dr. L S Vora','drlsvora@gmail.com'],
            ['Dr. Tejas J Patel','tejasjpatel29@gmail.com'],
            ['Dr. Chintan Kansagua ','info@primegastro.in'],
            ['Dr. Udit Godhki','cushahmedical@gmail.com'],
            ['Dr. Chirayu Chokshi','mmcmedical@gmail.com'],
            ['Iqbal','mc@mctrust.org'],
            ['Dr. Paras D Shah ','harmonyhospital11@gmail.com'],
            ['Dr. Arpan Shah','dr.arpanshah@gmail.com'],
            ['Ms. Nikita','biomed@kiranhospital.com'],
            ['mr.ramesh bhosle','rameshbhosale51@gmail.com'],
            ['Praful Pathi','pamrathod@yahoo.co.in'],
            ['Ram Das','bhavesh.thanekar@hiranandanihospital.org'],
            ['Raju','info@hjdghsh.in'],
            ['Bharat','bharat.pase@hindujahospital.com'],
            ['Shailesh','admin@shushrushahospital.org'],
            ['Dr. Shivahasan','cdshiva123@gmail.com'],
            ['Sachinkar','biomedical.mul@fortishealthcare.com'],
            ['Dr. Patil ','drpatilhospital92@gmail.com'],
            ['Uday ','uday.uttekar@adityabirla.com'],
            ['Dr. Uday Singh Patil','udaysinh.pratibha@gmail.com'],
            ['Rajesh Parmar ','biomedical@bhaktivedantahospital.com'],
            ['Jueli Pramod Pandar ( Ms. Poonam Has Left The Organization So She Asked To Call Jueli And Tatke Feedback)','biomedical@bhatiahospital.org'],
            ['Dr. Sudha Tandon','sudhantandon@gmail.com'],
            ['Dr. Sanjay Kadam','sanjaykadam13@gmail.com'],
            ['Dr. Chandrakanta','kalsekar.hospital@gmail.com'],
            ['Kanikar','kannikar.sanjeev@gmail.com'],
            ['Ashwajit','amitagrawal_80@rediffmail.com'],
            ['Amol','biomedical@hindujahealthcare.com'],
            ['Swamy','udaygiri2009@gmail.com'],
            ['Miss. Gaury Zade','biomedical.meditrina@gmail.com'],
            ['Dr. Makanand Patki','makarandpatki@gmail.com'],
            ['Nielsh Yeshwant Mal','biomedsupervisor.pune@columbiaindiahospitals.com'],
            ['Jayant','dhanwantaridadar@gmail.com'],
            ['Ms. Jyothi Gaikwad','biomedical.anh@gmail.com'],
            ['Dr. Varsha','otsupervisor@mmfhospitals.in'],
            ['Dre. Hemant Borse','hemant.borse@gmail.com'],
            ['Dr. Ajay Chauwan','dr.ajaysurgeon@gmail.com'],
            ['mr.virupkash kesti','virukesti@gmail.com'],
            ['Mr. Vinay Kuamr','biomed.mhg@tbs-india.com'],
            ['Gajanand Nagulkar','manikhospital@yahoo.co.in'],
            ['Dr. Anil Rathod','anilrathod577@gmail.com'],
            ['Dr. Nitin zabak','drzabak@gmail.com'],
            ['Dr. Amit Kele','dramitkele@gmail.com'],
            ['Dr. Devdatta Padhye','padhyedd@gmail.com'],
            ['Mrs. Shnehal','goenkagmc@gmail.com'],
            ['Dr.Shanshank Kadam','shakunclinic@yahoo.com'],
            ['Sanjay ','renu.singh@wockhardthospitals.com'],
            ['Dr. Anil Sanap','lifelinehospitalbeed@gmail.com'],
            ['Dr. Rakesh Patel','suyashendoscopy@gmail.com'],
            ['Dr. Amol Khot','aakhot@gmail.com'],
            ['Sunil','Sunil.kadam@globalhospitalsindia.com'],
            ['Dr. Niraj Swalakhe','sawalakhe_1@yahoo.com'],
            ['Bhagwan Bhonde','bhagwan.bhonde@gmail.com'],
            ['Pooja Nbilakar','pooja.pilankar@hiranandanihospital.org'],
            ['Dr. Rajesh Kmwad','drrajeshkomwad@gmail.com'],
            ['dr.girish borawke','drgirishborawake@gmail.com'],
            ['Dr.preetkal','preetkal@gmail.com'],
            ['Manoj','biomedical@jupiterhospital.com'],
            ['aman choukade','aman.choukade@althea-group.com'],
            ['Mr.Mohit','bmesaifee@gmail.com']
          ];
        }
        $bar = $this->output->createProgressBar(count($emails));
        $bar->start();
        foreach ($emails as $email) {
          // dd($email);
          Mail::to($email[1])
          ->send(new ReminderEmail($email[0]));
          $bar->advance();
        }
        $bar->finish();
        $this->comment(PHP_EOL."Command Completed");
    }
}
