<?php

namespace App\Filament\Resources\ArchiveServiceRequests\Schemas;

use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class ArchiveServiceRequestsInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('cvm_id')
                    ->placeholder('-'),
                TextEntry::make('import_id')
                    ->placeholder('-'),
                TextEntry::make('request_type')
                    ->placeholder('-'),
                TextEntry::make('sub_type')
                    ->placeholder('-'),
                TextEntry::make('customer_id')
                    ->placeholder('-'),
                TextEntry::make('hospital_id')
                    ->placeholder('-'),
                TextEntry::make('dept_id')
                    ->placeholder('-'),
                TextEntry::make('remarks')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('closure_remarks')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('sap_id')
                    ->placeholder('-'),
                TextEntry::make('sfdc_id')
                    ->placeholder('-'),
                TextEntry::make('sfdc_customer_id')
                    ->placeholder('-'),
                TextEntry::make('product_category')
                    ->placeholder('-'),
                TextEntry::make('employee_code')
                    ->placeholder('-'),
                TextEntry::make('last_updated_by')
                    ->placeholder('-'),
                TextEntry::make('status')
                    ->placeholder('-'),
                TextEntry::make('is_escalated')
                    ->numeric(),
                TextEntry::make('escalation_count')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('escalation_assign1')
                    ->placeholder('-'),
                TextEntry::make('escalation_assign2')
                    ->placeholder('-'),
                TextEntry::make('escalation_assign3')
                    ->placeholder('-'),
                TextEntry::make('escalation_assign4')
                    ->placeholder('-'),
                TextEntry::make('escalation_reasons')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('escalation_remarks')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('escalated_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('feedback_id')
                    ->placeholder('-'),
                TextEntry::make('feedback_requested')
                    ->numeric(),
                TextEntry::make('is_practice')
                    ->numeric(),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('acknowledgement_updated_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('acknowledgement_status')
                    ->placeholder('-'),
                TextEntry::make('reminder_count')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('happy_code')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('happy_code_delivered_time')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('acknowledged_by')
                    ->placeholder('-'),
                TextEntry::make('is_happy_code'),
            ]);
    }
}
